name: fanmi
description: 凡觅客户端版本v0.2

version: 0.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 设备信息
  device_info: ^2.0.2
  # 包信息
  package_info: ^2.0.2
  # 状态管理
  provider: ^5.0.0
  # 网络请求
  dio: ^4.0.0
  # 对话框
  flutter_smart_dialog: ^2.0.5
  # 列表刷新
  pull_to_refresh: ^2.0.0
  # 动画
  animations: ^2.0.0
  # 保存图片
  image_gallery_saver: ^1.6.9
  # 权限管理
  permission_handler: ^8.0.0+2
  # 图片缓存
  cached_network_image: ^3.0.0
  # svg矢量图
  flutter_svg: ^0.22.0
  # 屏幕适配
  flutter_screenutil: ^5.0.0+2
  # 展开文字
  expandable_text: ^2.2.0
  # 图片选择器
#  image_picker: ^0.8.0+3
#  multi_image_picker2: ^5.0.2
  wechat_assets_picker: ^6.0.2
  # 滑动组件
  extended_sliver: ^2.0.0
  # 页面切换动画
  page_transition: ^2.0.2
  # 七牛云插件
  qiniu_flutter_sdk: ^0.3.0
  # 文件路径
  path_provider: ^2.0.2
  # 本地缓存
  shared_preferences: ^2.0.6
  # 苹果登录
  sign_in_with_apple: ^3.0.0
  # 未读圆点
  badges: ^2.0.1
  # 微信登录
  fluwx: ^3.4.3
  image: ^3.0.2
  # qq登录
  tencent_kit: ^2.1.0
  # 极光推送
  jpush_flutter: ^2.1.2
  # 登录ui
  flutter_login: ^2.1.0
  # 网页展示
  webview_flutter: ^2.0.9
  # im sdk
  tencent_im_sdk_plugin: ^3.3.0
  # 元组类
  tuple: ^2.0.0
  # 加载组件
  flutter_easyloading: ^3.0.0
  # 弹跳特效
  flutter_bounce: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  #对话框
  adaptive_dialog: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/city.json

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/page_font.ttf
    - family: Hippo
      fonts:
        - asset: assets/fonts/Hippo.ttf
